### ISSUE TITLE
PrixCarburant_quotidien_{}.xml are not deleted

### ISSUE THREAD

**Issue by MisterTdog** [max5962/prixCarburant-home-assistant#10]
L'intégration PrixCarburant semble correctement installé sur HA (HACS). Elle semble correctement fonctionnement chez moi, mais j'ai des "tonnes" de fichier "PrixCarburant_quotidien_{date}.xml" qui s'accumulent... Ils ne semblent jamais supprimés.
Dans les logs j'ai :

`2021-07-01 14:45:01 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.prixcarburant_85500002 fails
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 350, in async_update_ha_state
await self.async_device_update()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 558, in async_device_update
raise exc
File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/prixCarburant/sensor.py", line 163, in update
self.client.clean()
File "/usr/local/lib/python3.8/site-packages/prixCarburantClient/prixCarburantClient.py", line 221, in clean
self.removeFile("station.csv")
File "/usr/local/lib/python3.8/site-packages/prixCarburantClient/prixCarburantClient.py", line 130, in removeFile
os.remove(file)
FileNotFoundError: [Errno 2] No such file or directory: 'station.csv'`

**Comment by lacrima08** [comment]
Bonjour,

Pareil de mon coté

**Comment by max5962** [comment]
mergé ! 
merci @ryann72 , si vous confirmez que c'est OK poru vous, je fermerait le ticket :)
