### ISSUE TITLE
Error while setting up prixCarburant platform for sensor

### ISSUE THREAD

**Issue by Mick51** [max5962/prixCarburant-home-assistant#18]
Hi, I have this error on the latest versions of home assistant.

`Logger: homeassistant.components.sensor
Source: custom_components/prixCarburant/sensor.py:73
Integration: Capteur (documentation, issues)
First occurred: 09:58:18 (1 occurrences)
Last logged: 09:58:18

Error while setting up prixCarburant platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/prixCarburant/sensor.py", line 73, in setup_platform
    stations = client.extractSpecificStation(list)
  File "/usr/local/lib/python3.9/site-packages/prixCarburantClient/prixCarburantClient.py", line 163, in extractSpecificStation
    stationsXML = self.stationsXML
AttributeError: 'PrixCarburantClient' object has no attribute 'stationsXML'
`

**Comment by forzewin** [comment]
Hello, j'ai le même problème :)

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/prixCarburant/sensor.py", line 65, in setup_platform
    stations = client.foundNearestStation()
  File "/usr/local/lib/python3.9/site-packages/prixCarburantClient/prixCarburantClient.py", line 207, in foundNearestStation
    stationsXML = self.stationsXML
AttributeError: 'PrixCarburantClient' object has no attribute 'stationsXML'

**Comment by pbranly** [comment]
Même problème de mon côté
