### ISSUE TITLE
Problème d'attribut ? 

### ISSUE THREAD

**Issue by Hydci** [max5962/prixCarburant-home-assistant#22]
Bonjour je viens de remarquer que dans mes logs j'ai ça comme erreur et depuis plus aucun prix n'est remonter sur mon interface voici les lignes de code d'erreur  
```
Error while setting up prixCarburant platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/prixCarburant/sensor.py", line 73, in setup_platform
    stations = client.extractSpecificStation(list)
  File "/usr/local/lib/python3.9/site-packages/prixCarburantClient/prixCarburantClient.py", line 163, in extractSpecificStation
    stationsXML = self.stationsXML
AttributeError: 'PrixCarburantClient' object has no attribute 'stationsXML'
```

**Comment by Aohzan** [comment]
Pareil de mon côté, le sensor est ok mais sans attributs

**Comment by carter013** [comment]
Idem pour moi, dans les attributs, les tarifs ne remontent plus ...

**Comment by Aohzan** [comment]
Comme il n'y a pas de news ici :(, j'ai fork l'intégration et pas mal retravaillé dessus pour la rendre plus pratique à mon goût (config flow, un sensor par carburant...)
Si ça intéresse https://github.com/Aohzan/hass-prixcarburant, attention un peu de modif de conf à faire, et la gestion des station selon la position est pas encore implémentée, mais ça viendra prochainement

**Comment by Aohzan** [comment]
Récupération des stations selon la position ajouté
