### ISSUE TITLE
New issue but do not know if it make it not working...

### ISSUE THREAD

**Issue by tikismoke** [max5962/prixCarburant-home-assistant#3]
Got this in logs...

```2020-05-20 15:18:35 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.prixcarburant_21000001 fails
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 279, in async_update_ha_state
    await self.async_device_update()
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 472, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/prixCarburant/sensor.py", line 144, in update
    self.client.clean()
  File "/srv/homeassistant/lib/python3.7/site-packages/prixCarburantClient/prixCarburantClient.py", line 217, in clean
    self.removeFile("station.csv")
  File "/srv/homeassistant/lib/python3.7/site-packages/prixCarburantClient/prixCarburantClient.py", line 128, in removeFile
    os.remove(file)
FileNotFoundError: [Errno 2] No such file or directory: 'station.csv'
```

**Comment by ludoz** [comment]
Same for me

**Comment by roumano** [comment]
+1

**Comment by tikismoke** [comment]
Last time I didn't do anything and it rework later...

**Comment by roumano** [comment]
Ca semble mieux, effectivement, merci !

**Comment by max5962** [comment]
mergé ! merci @ryann72
