### ISSUE TITLE
Error while setting up prixCarburant platform for sensor

### ISSUE THREAD

**Issue by ThibautLM** [max5962/prixCarburant-home-assistant#5]
Bonjour, 
l'application marchait très bien il y a un moment mais depuis peu j'ai cette rerreur dans les logs et les prix des stations que j'ai paramétré ne remonte plus... Depuis une MAJ de Home Assistant je pense.

L'appli est vraiment bien sinon merci pour le travail ! j'espère que vous allez continuer et trouver mon problème. 
Je suis a disposition si vous voulez plus d'informations. 

Les logs de mon journal HA : 

Error while setting up prixCarburant platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 199, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/prixCarburant/sensor.py", line 70, in setup_platform
    stations = client.extractSpecificStation(list)
  File "/usr/local/lib/python3.8/site-packages/prixCarburantClient/prixCarburantClient.py", line 159, in extractSpecificStation
    stationsXML = self.stationsXML
AttributeError: 'PrixCarburantClient' object has no attribute 'stationsXML'

**Comment by pbranly** [comment]
Hello
J’ai exactement le même problème 
Philippe

**Comment by max5962** [comment]
Bonjour,
Désolé je ne suis plus très présent, sur github et pas vraiment du temps perso pour finir reelement ce projet :/
Beaucoup de bugs que j'avais pas anticipé.

Je regarderais si je peux faire quelque chose :)

**Comment by valderaplets** [comment]
sur une install fraiche, j'ai aussi cette erreur, sur l'ancienne ça amrche toujours
