### ISSUE TITLE
Plus de remontée d'infos

### ISSUE THREAD

**Issue by vini59fr** [max5962/prixCarburant-home-assistant#9]
Salut

Depuis 2 jours, plus aucune remontée d'info et ce message d'erreur en log 

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 350, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 558, in async_device_update
    raise exc
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/prixCarburant/sensor.py", line 163, in update
    self.client.clean()
  File "/usr/local/lib/python3.8/site-packages/prixCarburantClient/prixCarburantClient.py", line 221, in clean
    self.removeFile("station.csv")
  File "/usr/local/lib/python3.8/site-packages/prixCarburantClient/prixCarburantClient.py", line 130, in removeFile
    os.remove(file)
FileNotFoundError: [Errno 2] No such file or directory: 'station.csv'

**Comment by max5962** [comment]
mergé ! merci @ryann72

**Comment by inrepublica** [comment]
Bonjour, je rencontre actuellement le même problème depuis plusieurs jours. J'ignore si cela est du à une nouvelle version de HA:
`
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:549
First occurred: 08:03:05 (5 occurrences)
Last logged: 08:03:05

Entity sensor.prixcarburant_62170002 (<class 'custom_components.prixCarburant.sensor.PrixCarburant'>) implements device_state_attributes. Please report it to the custom component author.
Entity sensor.prixcarburant_62170003 (<class 'custom_components.prixCarburant.sensor.PrixCarburant'>) implements device_state_attributes. Please report it to the custom component author.
Entity sensor.prixcarburant_62170005 (<class 'custom_components.prixCarburant.sensor.PrixCarburant'>) implements device_state_attributes. Please report it to the custom component author.
Entity sensor.prixcarburant_62600002 (<class 'custom_components.prixCarburant.sensor.PrixCarburant'>) implements device_state_attributes. Please report it to the custom component author.
Entity sensor.prixcarburant_76290001 (<class 'custom_components.prixCarburant.sensor.PrixCarburant'>) implements device_state_attributes. Please report it to the custom component author.
`

**Comment by ryann72** [comment]
Bonjour,

Merci pour ton retour, je n'ai pas ton erreur et pourtant je suis sur la 2021.12.8 de home assistant. 

Pour ce qui est de la date, il s'agit de la dernière date de mise à jour renseignée dans les Open data du gouvernement. Donc le dernier changement de prix effectué par la station. 
Je vais essayer de reproduire le problème quand j'ai un moment.

**Comment by inrepublica** [comment]
Merci de ton aide, si tu as besoin de plus de logs c'est sans problème. Faut juste m'expliquer où je peux trouver des logs plus verbeux.

**Comment by ryann72** [comment]
Je viens d'accepter la correction. 
Tu peux mettre à jour le composant via hacs.

**Comment by inrepublica** [comment]
Je viens d'installer la nouvelle version. Ça a fait un peu planter, il ne trouvait plus l'intégration... Après désinstallation / réinstallation cela a l'air ok ;-) Merci à toi.
